---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-dach
  namespace: monitoring
  labels:
    app: greeting-dach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-dach
  template:
    metadata:
      labels:
        app: greeting-dach
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: greeting-dach
          image: ammbra/techflow:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - name: prometheus-jmx
              containerPort: 9099
          env:
          - name: REGION
            value: dach
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/q/metrics"

---
apiVersion: v1
kind: Service
metadata:
  name: greeting-dach-service
  namespace: monitoring
  labels:
    app: greeting-dach
spec:
  type: LoadBalancer
  selector:
    app: greeting-dach
  ports:
    - protocol: TCP
      name: http-traffic
      port: 9080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: greeting-dach-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: greeting-dach
  endpoints:
    - port: http-traffic
      path: "/q/metrics"