---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-benelux
  namespace: monitoring
  labels:
    app: greeting-benelux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-benelux
  template:
    metadata:
      labels:
        app: greeting-benelux
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: greeting-benelux
          image: ammbra/greeting:0.0.23
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - name: prometheus-jmx
              containerPort: 9099
          env:
          - name: REGION
            value: benelux
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/q/metrics"
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-benelux-service
  namespace: monitoring
  labels:
    app: greeting-benelux
spec:
  type: LoadBalancer
  selector:
    app: greeting-benelux
  ports:
    - protocol: TCP
      name: http-traffic
      port: 9080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: greeting-benelux-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: greeting-benelux
  endpoints:
    - port: http-traffic
      path: "/q/metrics"