global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: 'greeting-cee'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'greeting-cee:80']
  - job_name: 'greeting-uki'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'greeting-uki:80' ]
  - job_name: 'greeting-benelux'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'greeting-benelux:80' ]